# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: npm CI

on:
  push:
    branches:
      - develop
      - master
    paths: [ 'quartz-manager-frontend/**' ]
  pull_request:
    branches:
      - develop
      - master

defaults:
  run:
    working-directory: ./quartz-manager-frontend

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:  [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./quartz-manager-frontend/package-lock.json
      - name: 'install'
        run: npm ci
      - name: 'test'
        run: npm test
      - name: 'build'
        run: npm run build --if-present
